#
# Weblate testsuite for Travis-CI
#
# - Test against all supported Django versions with postgresql
# - Test against all supported databases with current Django
# - Run Selenium tests on current Django
# - Test setup.py
#
dist: trusty
language: python
python:
  - "2.7"
install:
  - echo "No deps"
script:
  - sqlite3 < test.sql
  - python test.py
addons:
  apt:
    packages:
    - sqlite3
    sources:
    - travis-ci/sqlite3
